#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$application = new \Symfony\Component\Console\Application('Ping Drive', '0.0');

$application->add($defaultCommand = new \ForikalUK\PingDrive\Commands\PingDriveCommand());
$application->setDefaultCommand($defaultCommand->getName());

$application->run();
